services:
  - type: web
    name: excel-analyst-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
